### PR TITLE
Fixed some typos in Informed Lesson Three.

### PR DESCRIPTION
**Pull request by gspiers**
Thank you for the lessons, I'm really enjoying them.

### CODE REVIEW

**Comment by orta** [comment]
Awesome, thanks!

**Comment by gspiers** [comment]
Happy to help.

I wasn't sure, should I have fixed the same typos in the Playground file as well or are those generated from the readme.md files?

**Comment by orta** [comment]
They're not generated, so they're fine to fix too :dancers: - we seem to get so many typo fixes on this repo ;)

**Comment by gspiers** [comment]
At least not as many as the main Apple Swift repo ;) I added the playground fixes and a few others I found while doing the rest of the tutorials to pull request #24. Thanks!

**Pull request merged**
