### PR TITLE
Applied feedback from Lesson One.

### PR DESCRIPTION
**Pull request by ashfurrow**
- Added more explanation of for loops.
- Added more explanation about variables.
- Added some further-reading-style exercises.

### CODE REVIEW

**Comment by orta** [comment]
A good example to add at the bottom is a for loop with an if statement, might be worth adding?

**Comment by ashfurrow** [comment]
I like it.

**Comment by ashfurrow** [comment]
Done, with another mind-bendy thingy.

**Comment by orta** [comment]
Yes.

**Pull request merged**
