### PR TITLE
Playground 1-3

### PR DESCRIPTION
**Pull request by oisdk**
Did the first three tutorials as playgrounds.

Tried to do four and five, but a lot of it wasn't making sense in a playground. In both, since the tutorials walk you through making changes to code you've written yourself, it wasn't possible to directly translate them over into a playground. I tried to declare new types each time a change was made, (i.e., `ShowOne`, `ShowTwo`, `ShowThree`, `ShowFinal`, etc.) but it got confusing and messy. Maybe they're better as static markdown files?

### CODE REVIEW

**Comment by ashfurrow** [comment]
:+1:

**Comment by ashfurrow** [comment]
Makes sense, thanks!!

**Comment by oisdk** [comment]
No problem!

**Comment by orta** [comment]
Yeah, I think this makes the most sense, thanks @oisdk - great job!

**Pull request merged**
